### ISSUE TITLE
Css has lots of includes and cross references which makes it difficult to maintain/debug. We should revisit how we approach writing css moving forward.

### ISSUE THREAD

**Issue by master12** [ONRR/doi-extractives-data#2667]

**Comment by jeremiak** [comment]
I agree, here are some blog posts that inform my thinking on CSS maintainability:

- [Challenging CSS Best Practices (https://www.smashingmagazine.com/2013/10/challenging-css-best-practices-atomic-approach/)](https://www.smashingmagazine.com/2013/10/challenging-css-best-practices-atomic-approach/)
- [CSS and Scalability (http://mrmrs.github.io/writing/2016/03/24/scalable-css/)](http://mrmrs.github.io/writing/2016/03/24/scalable-css/)

Here is how we implemented a functional style on the FBI project: https://github.com/18F/crime-data-frontend/tree/master/sass/util

I like this approach because the classes are simple, easy to understand, and generally not modified once written which helps keep the CSS sane and clean.

**Comment by jennmalcolm** [comment]
This is part of tech updates, and is happening with Gatsby work (introducing CSS modules).
