### ISSUE TITLE
Tests are failing because of pivot-onshore.tsv is missing 2017 data

### ISSUE THREAD

**Issue by jeremiak** [ONRR/doi-extractives-data#2715]
## Expected Behavior
`npm run tests` should return no failing tests

## Actual Behavior
CircleCI is red [on builds, such as this one](https://circleci.com/gh/18F/doi-extractives-data/2875). This prevents us from merging cleanly. I was able to confirm that this is an issue across all branches by building without the cache on the `content-audit-edits` branch ([build with cache](https://circleci.com/gh/18F/doi-extractives-data/2874), [build without cache](https://circleci.com/gh/18F/doi-extractives-data/2876))

## Steps to reproduce the behavior
If using Docker, run `docker-compose run --rm jekyll npm run test`. Otherwise, just run `npm run test`

**Comment by jeremiak** [comment]
@master12 It looks like you updated some files near this in #2684 (specifically 1eef617e24e47de19f76417fe9a6daddd620315d), do you also have a `pivot-onshore.tsv` that got missed? If not, does this file ring a bell at all @mentastc? It looks like we just missed it in our 2017 update process.

**Comment by master12** [comment]
@jeremiak  I do not know how to create the pivot table but it appears to be used just for testing so we pushed the change. There is no documentation on the pivot table or what it tests. I did not look into it any further.

**Comment by jeremiak** [comment]
Ya, it is weird that it seems to only be used for testing. I noticed [this little bit in `/data/README.md`](https://github.com/18F/doi-extractives-data/tree/dev/data#tests):
> Note: If the tests fail, it is likely that you will need to update the pivot table (generally a file prefixed with pivot-) for that data. Read instructions on [creating a pivot table](https://github.com/18F/doi-extractives-data/blob/dev/data/Create-pivot-table.md).

The test is doing a data sanity check, but it is weird to use a file that is otherwise not used in the import process. I hate to keep merging failed/red pull requests so it seems to me that we should either:
* we should comment out the test
* try and re-generate the pivot table
* refactor the test to use otherwise existing data
* something else?

How do you think is best to proceed @master12?

**Comment by master12** [comment]
This is my opinion how i would proceed:

First I would comment out the test. 

Second create a ticket to explore this test further. Ticket Details:
1. Understand what it is testing?
2. Do we think it is a worthy test?
3. Refactor to not use/create a extra file for testing purposes.
4. If we cant refactor, write instructions on how to create the specifc pivot table. Dont need to copy and paste MS instructions on how to create a pivot table...

Third, since we are investigating an alternative to the make file data management I would wait to work on this ticket until we decided on what method we are using going forward.

@jeremiak  sound like a plan?

**Comment by jennmalcolm** [comment]
Not relevant with new data import process.
