### ISSUE TITLE
Add social icons to style guide

### ISSUE THREAD

**Issue by jenniferthibault** [ONRR/doi-extractives-data#2820]
From #2769 

## Expected Behavior
All interface patterns and components used (and re-used) on the website will be represented in the style guide, and patterns on the website will be used consistently.

## Actual Behavior
Icons for social media are used on the website but are not included in the style guide.
https://revenuedata.doi.gov/how-it-works/offshore-oil-gas/

![screen shot 2018-04-20 at 7 36 16 pm](https://user-images.githubusercontent.com/11636908/39371125-c8251cb8-4a0e-11e8-91c0-25e321974b29.png)

**Completion criteria:**
- [ ]  Add social icons to icon list in style guide
   https://revenuedata.doi.gov/styleguide/components/detail/icons.html

**Comment by jennmalcolm** [comment]
Next step: @mcharg review analytics to see if these links are being used.

**Comment by mcharg** [comment]
I don't think the numbers for the next page are quite right because there were 1,179 page views during the period and there are no where near that many showing up on the list of next pages, but it doesn't look like the links are being used.
[OffshoreOilGas.pdf](https://github.com/18F/doi-extractives-data/files/2064011/OffshoreOilGas.pdf)

**Comment by jennmalcolm** [comment]
This is not a priority.
