### ISSUE TITLE
Style guide: change icon class names to SVG file names

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2923]
We should replace the icon class names with the SVG file names in the style guide. The class names assume the font icon library, which we've recently abandoned in favor of SVG `includes`.

We should consider adding guidance for when and how to implement `_include` versions of the icons. For instance, the "Data and documentation" icon and linked text is deployed using an `include`.

**Comment by adborden** [comment]
@brentryanjohnson I'm a bit stuck on this one. Since the SVG includes are Jekyll liquid templates, they're not compatible with handlebars, so we can't render them in Fractal. I've been thinking about some other options, but nothing obvious is coming to mind. I'm curious if you had some thoughts here.

In order to use the SVGs in fractal, they need to be built by Jekyll first and then copied into the `/public` directory.

**Comment by adborden** [comment]
I was just looking at the map component in the styleguide and there's a similar issue where we need to reference the compiled maps. So it's leaning me toward thinking that the build order needs to change up a bit.

webpack -> jekyll -> styleguide

And the styleguide will pull assets from `_site`.

**Comment by brentryanjohnson** [comment]
Understood, @adborden. Let's figure out a time to discuss how to approach this.

**Comment by adborden** [comment]
In sprint planning we decided to de-prioritize this because the style guide framework is in flux. We'll take another look at it next sprint.

**Comment by jennmalcolm** [comment]
Closing since we're starting fresh with a new pattern library.
