### ISSUE TITLE
Ideas for key statistics on the home page

### ISSUE THREAD

**Issue by usEITI** [ONRR/doi-extractives-data#2945]
In an effort to get more timely data on the portal that satisfies the WH and Secretary's Office data requests we would like to see production, revenue (federal and Indian) rolled up on a monthly basis.  This will also help us demonstrate an evolution in the site.

**Comment by jennmalcolm** [comment]
Here's a file with some data that Data Retrievel is providing within the Department on a monthly basis. Perhaps we can include this data in our high level numbers on the home page. 

[Production Volumes May 2017 through May 2018.xlsx](https://github.com/18F/doi-extractives-data/files/2116789/Production.Volumes.May.2017.through.May.2018.xlsx)

**Comment by jennmalcolm** [comment]
@NBrannberg, do you have any other ideas for key stats you think would be good on the home page?

**Comment by NBrannberg** [comment]
Sales Year Data comes to mind :) 

Yes, we are in the process of compiling examples of all the suggested data sets we think make sense to present at a high level in addition to the data already available.

**Comment by mcharg** [comment]
Can we define the user tasks we think the key stats should support?

Here's a start:
- Get a quick temperature of the  current numbers.
- Know what has recently been updated.
- Understand the volume for the largest commodities.
- Understand how revenue and disbursements amounts fit together.
- Understand whether the current year numbers are on track to match the previous year numbers.

Anything else to add?

**Comment by mcharg** [comment]
Here are a couple of ideas.

Option A
https://1rn7bf.axshare.com/#g=1&p=option_a

Option B
https://1rn7bf.axshare.com/#g=1&p=option_b

**Comment by NBrannberg** [comment]
I really like Option A visually.  I'm impressed with your prototypes so far Shannon!  I really liked the disbursement prototypes Jennifer shared with us during today's demo as well.

**Comment by jennmalcolm** [comment]
Yes, thank you, @mcharg. These are both good options. One thing to note is that if we're going to call out the most recent month, we should probably allow for a couple month delay (e.g. use March instead of April here). Since reporting is not required for 45 days, the numbers are very unreliable so soon after the production month.

Another thing to think through is how to maintain consistency with this data and the production data file and numbers on the explore data page. Perhaps we use the file we have for download for the past year's data and call out that the "as of" date for the current year data. That's just one of many ideas that could work, so we can think about other options.

Also, let's try a version of A broken down by federal and Indian totals.

**Comment by mcharg** [comment]
I refined the first two options to better incorporate actual numbers and added a third option that attempts to explain the process.
https://1rn7bf.axshare.com/

**Comment by jennmalcolm** [comment]
Thank you @mcharg . Since Mike Deberarard was an advocate for adding Sankey diagrams, perhaps we could see if he's available to participate in this round of reserach. Let me know if you want me to do that.

**Comment by mcharg** [comment]
@jennmalcolm Sure, let's see if he wants to participate.

**Comment by mcharg** [comment]
@brentryanjohnson What are the blue dots supposed to signify?

**Comment by brentryanjohnson** [comment]
@mcharg They represent oil production quantities. The legend got cut off in the screenshot.

**Comment by mcharg** [comment]
Added two new options and gave each one a different title on the page, so we can test out a few of those.

https://1rn7bf.axshare.com/
