### ISSUE TITLE
Plan for taking over ONRR social media accounts

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2956]

**Comment by jennmalcolm** [comment]
@mentastc have you found out from Heidi yet on how close we are to taking these on? Does she want us to put the proposal together to go to the ELT?

**Comment by jennmalcolm** [comment]
@mentastc we are approved to take over the accounts, but I guess there is a training (through the Department) that you have to take before we can start posting. Next step is to find and take this training. I would like both you and @Maroyafaied to take it if possible.

**Comment by mentastc** [comment]
Last email I have from the department they said that the training doesn't exist yet, I believe we are good to start using social media.

Here's the email from coms
![image](https://user-images.githubusercontent.com/15347998/42651235-d6a67dd6-85dc-11e8-8619-02e2d0772aa4.png)

**Comment by mcharg** [comment]
Idea for the first Twitter post: a play on the rogue National Park Service where we say the open data team (the open data NRRDs?)  has taken over the Twitter account.  I don't think anyone has posted for over a year, so it could be a fun way to jump start new posts.

**Comment by jennmalcolm** [comment]
@mcharg and @brentryanjohnson I'm setting up a meeting on Monday to discuss branding ideas for social media. We can create new issues for anything that comes up during that meeting or reflect it in #2939. We have a schedule in the content calendar #2800 . Once we have the branding and privacy impact analysis done, we can start posting. Since that's a plan, I'm closing this issue.
