### ISSUE TITLE
Review the sustainability of  CO opt in state content

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3105]
review the content of one of the four states and see if it is realistic to recreate those pdfs.

**Comment by Maroyafaied** [comment]
here is my work finding the data for Colorado
1. Found all the data for the revenue stream pdf, I didn't find any rates or fees that needed to be updated for any of the commodities but included all links in case.
2. Found some sources of revenue data for Colorado but not in depth of detail as in the site currently
3. Found disbursement data  available by fund, by division, break down of severance tax distribution and breakdown by federal mine lease. Again, didn't find it in the same breakdown or detail as currently in the website
4. Emailed the contacts that we got the data from previously, haven't heard back. 

https://docs.google.com/spreadsheets/d/1XoJakHixYNU0kN5Qbf_HgqgmaUiC2hnzmJAURw9Ntus/edit#gid=1234553179

**Comment by jennmalcolm** [comment]
@Maroyafaied, do you have any updates on whether you've heard back from the emails about some of the data we were missing? Also, could you document your recommendations in this issue or in your spreadsheet on a separate tab what you recommend we remove/archive from the CO state page due to sustainability issues?

**Comment by Maroyafaied** [comment]
I made recommendations on the spreadsheet and included the response form the contact I had. I am closing this issue. Thanks
