### ISSUE TITLE
Explore other options for federal revenue graphic

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3176]
Since it didn't perform well in user testing, we should consider changing to the table view we tested for Indian revenue or other options for displaying federal revenue.

Goals of the design:
* Make it easy for users to understand the revenue amounts for each phase
* Help users understand what the phases are
* Incorporate the content that is in the current revenue graphic
* Ensure the design can be responsive to work on mobile
* Don't unnecessarily repeat content we have in other places

What we know from research:
* Participants (at least 9 participants across studies) had a difficult time understanding the revenue graphic.
  * The scale made it difficult for users to understand the numbers for anything other than During Production Oil & Gas.
  * Participants had a difficult time figuring out what the scale of the bars was.
  * Many didn't read the column headers and very few click on the Details tab.

* Participants loved the table designed for Native American revenue (7/12 picked it as their favorite option, plus 2 that had a positive reaction).
  * They found it really easy to understand.
  * The design used the headings Bonus, Rents, Royalties, and Other Revenue
  * Some wanted the columns to be sortable.

* The current glossary icons have been problematic, particularly in table headers for other designs (at least 7 participants across studies have had problems), and we're starting to see use cases beyond strict definitions for contextual healp.

Design: https://etoy5p.axshare.com/

**Comment by mcharg** [comment]
@jennmalcolm @brentryanjohnson 
How's this?  It uses the model from Native American revenue, but adds the shaded rows to differentiate the non-commodity revenue.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/a79d91e3-fab6-45bf-9fc4-f0ada65f6d96)

**Comment by brentryanjohnson** [comment]
👆 I think this is an improvement, but it's weird to me to have a row labeled "Other revenue" with a column labeled "Other revenue." It also seems like this section might then be perceived as a breakdown of the Other revenue column. It might also raise the question of why this section of other revenue itemized out (to some extent), but the columnar other revenue is not? At the very least, we probably need to explain what "other revenue" entails in each of these instances.

Perhaps there is a way to separate it with another table header, which might clarify the section and eliminate the redundancy? This example might be problematic, though, because it detaches the total row in a way that might imply the total is just the other revenue section. 

![Table of commodities and revenue](https://user-images.githubusercontent.com/32855580/53126906-1175db80-3516-11e9-9791-849a7ab3297a.png)

**Comment by mcharg** [comment]
Maybe somebody can dig into what that other revenue actually is.  I was just going by what's in the tiny footnote to the current chart.

**Comment by brentryanjohnson** [comment]
@jennmalcolm or @mentastc, what's the difference between other revenue associated with a commodity and other revenue _not_ associated with a commodity? 

Should we just total up commodity revenue and other revenue separately, and then perhaps combine them further down the table?

**Comment by jennmalcolm** [comment]
Based on the definition  for the other revenue column, it includes minimum royalties, estimated royalties, settlement agreements, and interest. Those types of revenues are still associated with commodities but are just small enough that they were thrown into the leftover bucket. There are some types of revenues that are not associated with a commodity. Offshore inspection fees do not have an associated commodity. I know that civil penalties are  assessed at a company level so not tied to a specific property or commodity. 

I think it would help clarity to have one line for the non-commodity revenues. I also think it's confusing to have revenue types in both columns and rows (at the end).  We could combine all the non-commodity revenues into one line that says non-commodity in the first column and has that total in the other revenue column or create a separate little table with the columns for the non-commodity being inspection fees, civil penalties, and other. If we just leave it as one row and the end of the table, could we then just add non-commodity to the glossary for an explanation?

**Comment by mcharg** [comment]
How's this?  The question mark icon also has another use case in the disbursements design, so it would become a new pattern.  You can click on it in the prototype.
https://etoy5p.axshare.com/#g=1&p=revenue

**Comment by jennmalcolm** [comment]
I think that looks clearer. I'm not quite understanding the purpose of having the question mark for help and the glossary. What are the two distinct use cases for when we would use each? It seems strange to me that the results of both look the same.

**Comment by mcharg** [comment]
The idea is that there are some cases where it's not strictly a definition we want to convey.  Maybe we just switch to a question mark for both since we don't want users to have to think about the difference...

**Comment by brentryanjohnson** [comment]
Agreed. In my mind, the glossary implies the explanation of an uncommon and/or technical term, which is distinct from elucidating the intended meaning or context of a specific term which may otherwise be commonly understood. For example, "other revenue" isn't particularly uncommon or technical, but may require explanation of what it entails or the particular context of each use the term.

I think this is only an issue at the moment because of the book icon and the past use of the glossary. I agree; we should probably explore using a question mark or something similar for both, and then we can use one UI routine that is more flexible and fulfill both use cases.

**Comment by jennmalcolm** [comment]
Understood, if we end up using two different icons, it should be more clear to users what the difference is and why. We use the glossary for terms like "production," which doesn't seem technical to me.

**Comment by mcharg** [comment]
This version uses a question mark for both cases.
https://etoy5p.axshare.com/#g=1&p=revenue

**Comment by mcharg** [comment]
See #3691 for copy
