### ISSUE TITLE
Determine, request, and configure domain for blog

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3217]
We need a domain for the blog. First, we should decide if the blog will be part of doi.gov or onrr.gov. Then we should choose a subdomain and/or path. We then need to request the subdomain through DOI/BSEE and configure in Federalist.

Here are a few ideas:

- revenuedata.doi.gov/blog
- innovationblog.doi.gov
- onrr.gov/blog
- blog.onrr.gov
- idm.doi.gov

**Comment by jennmalcolm** [comment]
@brentryanjohnson, thanks for bringing this up. I'm somewhat torn on whether it should be a DOI or ONRR domain. While NRRD is a DOI site, I think we may want to expand the scope of the blog to other ONRR topics, especially as IDM takes on public affairs responsibilities. I like the idea of one of the ONRR URLs. Probably whatever we go with, we should communicate it to ONRR's executives for awareness.

My initial thought before you proposed and options was that revenuedata.doi.gov/blog would be the easiest. We wouldn't need to submit a request to anyone for that, right? If we went with this and then decided a different domain would be more appropriate, we could always change it.

@usEITI, what do you think about this since you will be in charge of public affairs soon?
