### ISSUE TITLE
Evaluate whether our data is set up to appear in Google's new Dataset Search

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3226]
Details are here:
https://www.blog.google/products/search/making-it-easier-discover-datasets/

**Comment by lpgoldstein** [comment]
No. I tried various search terms to find our data in the tool and then also tested out the site on on the structured data testing tool and nothing showed up. https://developers.google.com/structured-data/testing-tool/

Here is the link that will guide us on how to structure our data within the code so that our datasets will appear: 

https://developers.google.com/search/docs/data-types/dataset
