### ISSUE TITLE
Figure out a presence for NRRD on ONRResource

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3246]
- [x] Evaluate ONRResource pages and determine best way to integrate NRRD
- [ ] Contact the web team to get next steps
- [x]  Draft content for weekly message for Jim S. about NRRD

**Comment by Maroyafaied** [comment]
attached is a draft for Jim S.  weekly message content on NRRD, I gave access to everyone on the team. https://docs.google.com/document/d/1tg_-dVmXqK_76ZFp2Hdd9CBbxayHodfHLq6HaqLOPjw/edit

**Comment by jennmalcolm** [comment]
Message looks good. Jim was asking for one, so I sent him what we currently have, and it will be his next message. Thanks.

**Comment by Maroyafaied** [comment]
Great, thanks!

**Comment by Maroyafaied** [comment]
Findings: 
- Home > About US> ONRR Information ( list of all programs but no mention or IDM program, and when you click on “ONRR information, you get a chart where all the programs are clickable but not IDM)
- Under Operations tab there is Data Governance, FOIA, no other IDM teams.
- Under Work Resources tab there is Project management program, no other IDM teams.

Recommendations:
- I recommend for NRRD to have its own separate tab on top  or put under About Us or Work Resources Tab.
- I recommend for IDM to have it’s own page under ONRR information since it’s the only program that doesn’t have one, with all the appropriate teams under it rather than being spread out on different tabs.
