### ISSUE TITLE
Responsive design for final home page

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3282]
The biggest piece will be figuring out what to do with the tabs at the top of the page, which is going to require looking at a few different options.

**Comment by jennmalcolm** [comment]
I was going to come in here and make suggestions on links in the How it Works page to use, but I see that, as usual, you are a few steps ahead of me. I think what you picked for production and revenues is perfect, but I have concerns about the disbursement link leading to the budget process info. Although somewhat connected, I don't think that info explains disbursements. I don't think we have a good place to link for that one, which makes me think maybe we should create a more general disbursements section in How it Works, and LWCF, and HPF fund info (which we already have) could be two of the sub-topics. What do you think @brentryanjohnson?

Obviously that wouldn't be done before this is built, so for now, I think maybe we could just use the explore disbursement data link there. Is that reasonable @mcharg?

**Comment by jennmalcolm** [comment]
I'm really not comfortable with calling the link to the budget process "Learn about disbursements" because the budget process is only tangentially related to disbursements. Disbursements are generally governed by laws outside of the annual budget process (GOMESA, Alaska Statehood Act, Energy Policy Act of 2005, etc). The times  that the budget process affects disbursements are limited to things like the budget sequestration of 2013. 

Here are some options I could live with:
1. Change the current link name to "Learn about the budget process." This is definitely not a good option for your design consistency, but at least it's accurate. 
2. I still think we could just plug the explore disbursement data link back in there until we develop proper disbursements content on the how it works page.
3. Link to the search results from disbursements (https://revenuedata.doi.gov/search-results/?q=disbursements) because then at least they have a few options directly related to disbursements.
4. Ignore my suggestion from yesterday, and just change all of the links back to the explore data ones.

**Comment by mcharg** [comment]
1. I like this option best because it best meets the goal to send users to content about how disbursements work.
2. I think this would be more inconsistent with the other tabs than changing the label.
3. I think it would be jarring to send users to search results from a prominent home page button.
4. I think it's good to have links to the how it works content.

@brentryanjohnson Do you have thoughts?

**Comment by brentryanjohnson** [comment]
@mcharg and @jennmalcolm We should develop disbursements contextual content. I think we should omit a link to the budget process for now, since it really isn't getting at what we want.

Can we carve out some time to scope this in DC?

**Comment by jennmalcolm** [comment]
Created #3321 for disbursements content work.
