### ISSUE TITLE
Add banner to pattern library

### ISSUE THREAD

**Issue by master12** [ONRR/doi-extractives-data#3298]

**Comment by master12** [comment]
For review:
https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3298-banner-pattern-lib/patterns/components/banner/

**Comment by brentryanjohnson** [comment]
I changed the README text from:

> This is the banner that appears at the top of all our pages on the site. There are no properties to pass in it is a very simple component.

to:

> This is the banner that appears at the top of all our pages on the site. It's a simple component, so there are no properties to pass in.

The component text is self-explanatory, so I've limited the edit to grammar (for now).

**Comment by brentryanjohnson** [comment]
We should consider (in a future sprint) adding a "Here's how you know" drop to this component, as seen here: https://designsystem.digital.gov/components/

Since this pattern could be deployed on any site with HTML and CSS, it helps to explain how the user can be confident it's an official government website.

**Comment by jennmalcolm** [comment]
Work continuing in #3293
