### ISSUE TITLE
B & C OGOR Data for NRRD lease/well level production

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#3331]
Pull OGOR (B & C and maybe A again) production data by month for several years.

**Comment by mentastc** [comment]
@mcharg I've uploaded ogor A B & C data that may help you with your questions for what fields they would  want to see. the file is located here: https://drive.google.com/file/d/1C0UwtzadZRTdPDEgQ94k88m6-JHQX1yF/view?usp=sharing

**Comment by jennmalcolm** [comment]
@mcharg I can probably answer some of your questions at our meeting today. Also, have you looked at the production reporting handbook for any definitions? https://www.onrr.gov/ReportPay/Handbooks/index.htm

**Comment by jennmalcolm** [comment]
Closing this since we have the data available and can move along in the research process.

**Comment by jennmalcolm** [comment]
A well is tied to a contract, but there may be multiple wells on a contract, so we will need to download that too. @mentastc, can you get it from MART?

**Comment by mcharg** [comment]
@mentastc I forgot to mention this as a blocker in standup.

**Comment by mcharg** [comment]
@mentastc Turns out I was looking at the wrong Excel file.  It may have been one from the previous pull you did.  The file linked above does have OGOR A and the well number, but I think we still may need to tie it to something that tells us about the lease, contract/agreement, operator, reporter, etc.
