### ISSUE TITLE
Correct federal revenue by company dates

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3390]
Update dates to show through 2017 for available federal revenue by company on this page: https://revenuedata.doi.gov/downloads/

![image](https://user-images.githubusercontent.com/30806839/48802965-a7fbec00-ecde-11e8-8073-3d81df8167c8.png)

**Comment by brentryanjohnson** [comment]
This is [fixed in `dev`](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/dev/downloads/#revenue), so it will be fixed on release @jennmalcolm. I eliminated that entry when I combined the revenue files.

![revenue entry on downloads page](https://user-images.githubusercontent.com/32855580/48803163-0b2d5480-ecc6-11e8-908c-e56ecbc0832a.png)

**Comment by brentryanjohnson** [comment]
Although I did notice the nav item still reads "Federal revenue by location," so I'm going to push a commit for that.
