### ISSUE TITLE
Consider adding message for IE user

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3447]
We've discussed it before, but I think we should again consider adding a message for any IE users that our site works better on other browsers. Maybe we could encourage enough people to use something else so we would no longer need to support IE.

**Comment by mcharg** [comment]
Here's an example of this kind of messaging I get when I visit Github on my iPad.
![img_1040](https://user-images.githubusercontent.com/38465926/49589381-4327cf00-f937-11e8-8b9e-276e5132c3a5.PNG)

**Comment by mcharg** [comment]
Will design this sprint and implement later.

**Comment by brentryanjohnson** [comment]
Here is some draft wording:

> We aim to make our website work for everyone, but some older web browsers may not properly display every feature on this site. If it looks like something isn't working as it should, try using a different browser, such as Chrome, Edge, or Firefox.

This message assumes only IE users will read it.

I have some concerns about this, namely:
- Even though this is something every development team faces, it can't help but come off a bit like: "We're asking you (user) to change your behavior because of our limitations," which isn't ideal.
- Naming browsers feels like an endorsement (or a condemnation), which we don't want to do. On the other hand, we have to give users an idea about how to interact with a functioning version of the site, which in this case means _not_ using specific browsers or versions of browsers. It seems like we must name the alternatives.
- I don't think our design should include a manufacturer's logo (when the time comes for that) as the above example does.

**Comment by mcharg** [comment]
@brentryanjohnson I think the draft wording works.  The only other option would be to explain that IE is being replaced by Edge by Microsoft to bring awareness to users that they're using a browser that is no longer being fully supported by the manufacturer to make it clear why they may see problems on out site (and other sites).

**Comment by mcharg** [comment]
@brentryanjohnson How's this?
https://2lqg2z.axshare.com/

**Comment by brentryanjohnson** [comment]
@mcharg It looks good. Unobtrusive, yet noticeable.

What do you think about making the ✖ symbol slightly more prominent, using the [unicode](https://www.fileformat.info/info/unicode/char/2716/index.htm) symbol instead of an "X"? Something like this? 

![warning about old browsers](https://user-images.githubusercontent.com/32855580/49890457-f3467d80-fdf8-11e8-9fac-b4a74345f37e.png)

**Comment by mcharg** [comment]
I found a close X in our icon set.
https://2lqg2z.axshare.com/

**Comment by mcharg** [comment]
@usEITI @jennmalcolm Please review and see if you are comfortable with this messaging.

**Comment by jennmalcolm** [comment]
Next step in #3496
