### ISSUE TITLE
unit measurement on annual and monthly gas charts

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3485]
We received feedback from a person attending the internal outreach regarding the label on units for both the annual and monthly gas charts. For annual charts,  he is suggesting instead of labeling it as "7 b mcf" to instead label it as " 7 Tcf" which is more standard way. So instead of it reading as " 7 billion million cubic feet" it would read " 7 trillion cubic feet". 

For the monthly charts, he is suggesting instead of labeling it " 400 million mcf" to label as " 400 bcf".

![image](https://user-images.githubusercontent.com/40175688/50100139-f49eee00-01dc-11e9-8cc6-e7a777243a63.png)
![image](https://user-images.githubusercontent.com/40175688/50100253-40ea2e00-01dd-11e9-9318-a7526b65be07.png)

**Comment by jennmalcolm** [comment]
Since mcf is the unit that the production is reported in, I lean toward keeping that. I also think we should keep the unit the same between all the gas charts. I know the true unit is cubic feet, and the letter before is just representing scale, but I think it will confuse people to use mcf in some places and bcf and tcf in others. I think mcf is more standard and so many less confusing to people outside of the industry. What's your opinion @Maroyafaied?

**Comment by Maroyafaied** [comment]
Yes, I agree to keeping it as mcf to keep it the same for all the tables.  I wanted to make sure that we look into his feedback but I will close this issue since we are not making any changes.
