### ISSUE TITLE
Design for archive

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3539]

**Comment by brentryanjohnson** [comment]
We have a number of content assets (pages, sections, PDFs, directories, timelines) that need to be archived. We can lock down this content and exclude them from the build process, leaving only the compiled assets and link to them.

We can use the existing subheading/column style on the how-it-works default page. The whole page will be branded as the USEITI archive (even though some content assets weren’t mandated by the EITI Standard).

## Single page for archive (/archive)

**Template:** (/how-it-works)
**Intro:** The United States participated in the [Extractive Industries Transparency Initiative (EITI)](https://eiti.org/) from 2011 to 2017. EITI is a voluntary, international standard that promotes open and accountable management of natural resources. This site was originally created to publish the USEITI annual report as interactive data and supporting information.

In November 2017, the U.S. government decided to no longer formally implement the EITI Standard, but remains a strong supporter of the good governance and the principles of transparency represented by the EITI.

The goal will be to exclude the following from the build process and simply maintain the compiled, static output. That could be a problem if we change CSS or behaviors for the rest of the site that affects these archive pages. We'll need to audit them from time to time.

Also, we'll need to figure out the best way to include the static opt-in charts in the archived state pages. My thought was that we could simply include the static HTML that's generated in `_site`, but that markup contains `react ids`. @master12 Can we relocate this static markup without creating duplicate ids or creating collisions?

## Archive sections

### History and timeline (currently on /about/ page)

### Executive summaries (2015, 2016, 2017)
- Extractive revenue appendix (2015)

### Audits and Reconciliation
- Budget audit factsheet
- Audits and assurance process fact sheet
- Reconciliation (2015, 2016)

### States and counties
- Opt-in state pages
  - State revenue streams (opt-in states)
  - Wyoming archive
  - Colorado archive
  - Alaska archive
  - Montana archive
- State laws and regulations
- Case studies (12 subpages)

### Economic impact
- Gross domestic product (GDP): The Bureau of Economic Analysis publishes data about the role of extractive industries on gross domestic product.
- Wage and salary jobs: Wage and salary data, from the Bureau of Labor Statistics, describes the number of people employed in natural resource extraction that receive wages or salaries from companies.
- Self employment: Self-employment data, from the Bureau of Economic Analysis, describes people who work in natural resource extraction, but don't receive wages or salaries because they own their own companies.

**Comment by brentryanjohnson** [comment]
Starting to build out the archive based on the markup in how-it-works.

![Archive page with USEITI logo and history and timeline](https://user-images.githubusercontent.com/32855580/52512465-c379e300-2bb9-11e9-99e7-c622bdc3449e.png)

**Comment by brentryanjohnson** [comment]
The draft archive design is in [this archive branch](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/archive/archive/) for your review, @jennmalcolm and @mcharg. 

I'm not yet opening a PR for the following reasons:

- This is currently in Jekyll; I need to port the code over to Gatsby
- We need to build out pages for the opt-in state content
- This stage meets the requirements of the current issue

**Comment by mcharg** [comment]
Looks good to me.

**Comment by jennmalcolm** [comment]
I agree. I like the structure and that we will be consolidating the EITI info and data we are not updating. The timeline for EITI is better here, and unnecessary in the about page now (#3583).

**Comment by brentryanjohnson** [comment]
We have our design in place for the archive. Next steps (in this order):

1. Build archive pages for opt-in states and migrate opt-in content from current state pages to new pages (#3629)
1. Repair and test links
1. Restructure state summary content (#3277)
1. Remove content that will not be archived in its current form (i.e., economic impact data, which will now just link to the agencies that provide the data)
1. Remove archived assets from build process (we need to scope this and figure out if it's desirable) _optional_
