### ISSUE TITLE
Build Reconciliation page in Gatsby

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3565]
https://revenuedata.doi.gov/how-it-works/reconciliation/

**Comment by jennmalcolm** [comment]
Since this one is being archived, I thought we were not going to transition to Gatsby. @master12, for this and others, like the case studies, didn't you say there's a way to leave in Jekyll but not have the same issues (e.g. long build time) like we have now? I think you said we could just take these archived pages out of the build process since we will not be updating them.

**Comment by brentryanjohnson** [comment]
I share @jennmalcolm's take, and have been planning to link to the compiled pages for reconciliation. There are a few things we should keep in mind if we do that, though:

- It will be difficult to audit content and keep track of links, since we rarely look at the compiled output (we're usually looking at the pre-compiled codebase)
- shared components (such as header, footer, nav, etc), will be static on the static pages; I don't believe there's a way to update them if we change those components for the rest of the site. That could lead to some problems down the road.

@master12 and I need to work out the best way to manage these archived assets from a technical standpoint. I'll add something to his calendar. Let me know if either of you want to join us for that discussion, @mcharg and @jennmalcolm.
