### ISSUE TITLE
Create a component/include for potential shutdown

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3612]
In the case of another shutdown, we need to have a message on our site saying the status of updating our site. 

Here is an example:

“Due to the federal government shutdown, this website will not be updated until further notice. More information is available at our agency's main website."

We should not release this message to the site until the day when we work to ensure an orderly shutdown, which would be Tuesday, I believe, but I would like to have it ready in case we need it.

**Comment by brentryanjohnson** [comment]
Here is a draft design pattern for a shutdown notice banner. Please have a look @jennmalcolm and @mcharg. This is only available on the Jekyll portion of the site right now; I'll need to create the component for Gatsby as well, once approved.

![homepage of revenuedata.doi.gov showing a banner that says Due to the federal government shutdown, this website will not be updated until further notice](https://user-images.githubusercontent.com/32855580/52597690-80617f00-2e08-11e9-8abb-7c9d3a1e252e.png)

**Comment by jennmalcolm** [comment]
This looks good to me.

**Comment by brentryanjohnson** [comment]
I suppose "further notice" just means "when the shutdown is over," so we should probably rephrase that?

**Comment by jennmalcolm** [comment]
Yes, @brentryanjohnson that probably is what that means, so I think that would be a good modification.

**Comment by mcharg** [comment]
I like the active voice better, as well, and agree with the modification to "when the shutdown is over".

**Comment by brentryanjohnson** [comment]
It looks like we may not need this immediately, after all 🤞. But I want to get it right, since we won't be able to update it after the fact, if there is indeed a shutdown.

Reading this again, it felt redundant: "Due to the government shutdown, we will not be able to update this site until the shutdown is over."

This is a bit longer, but it doesn't feel as awkward to me: "Due to the government shutdown, we are not able to update this site. We will resume work on the site when the shutdown ends."

![image of a yellow banner that says due to the government shutdown, we are not able to update this site - we will resume work on the site when the shutdown ends](https://user-images.githubusercontent.com/32855580/52649745-b8ff6800-2e9d-11e9-96d3-73c1b3976fb1.png)

Thoughts @jennmalcolm and @mcharg?

**Comment by jennmalcolm** [comment]
Yes, @brentryanjohnson, your second version is better. Hopefully we won't need it, but it's good to be prepared for future possibilities anyway.

**Comment by mcharg** [comment]
I think it works.

**Comment by brentryanjohnson** [comment]
The Gatsby component is finished as well. Here is how we add the alerts to each portion of the site:

## Jekyll
1. Go to `_layouts/default.html`
2. Add `    {% include shutdown-banner.html %}` in the `<body>` tag under the banner include

```
<body>
   {% include layout/banner.html %}

   {% include shutdown-banner.html %}

   {% include layout/header.html %}
```

## Gatsby
1. Go to `gatsby-site/src/layouts/index.js`
2. Add the `<AlertBanner />` component under the `<Banner />` component

```
</Helmet>
<Banner />
<AlertBanner />
<Header siteMetadata={data.site.siteMetadata} />
```
