### ISSUE TITLE
Review social media strategy and roles

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3648]
We should look at what's gone well and what we need to work on to ensure we are getting as much out of our access to social media as we can.

We will document any decisions we make for strategies going forward.

**Comment by brentryanjohnson** [comment]
Questions I drafted to help guide our discussion:

- Who is speaking when we use social media?

- What are the characteristics of that voice?

- Who follows us on social media?

- What do those followers expect from our social media?

- What happens if we don’t use social media at all?

- What does social media enable for us that other tools, outreach, or platforms do not?

- What is going well with how we’re using social media?

- How can we use social media in ways we are not yet using it?

**Comment by jennmalcolm** [comment]
@mentastc and @Maroyafaied do you think this issue is done, or do we still have more documenting to do?

**Comment by Maroyafaied** [comment]
I believe this issue is done but we need to create another issue to define and document responsibilities for Chris and I.@mentastc do you agree?

**Comment by Maroyafaied** [comment]
This is the document that Ryan was documenting as we were discussing the questions above. https://docs.google.com/document/d/1WJDBvxAmDVyOG4Mi3HtTgjXwKdK2AboovjNmhJ24nnI/edit
