### ISSUE TITLE
Analyze solids data to understand what's available

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3673]
I'll do a similar chart to what I did for oil and gas to outline the fields and what we should show.

**Comment by mcharg** [comment]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/a83b6ffc-6225-45d9-b289-2c43dd5677d9)

Visio file (limited access): https://drive.google.com/open?id=1nlpDOxAzyyhEIIuMghC-ivNaswzZTUhp

**Comment by mcharg** [comment]
Updated to reflect that solids don't have agreements.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/1567429c-f629-4d51-8864-69090e51aa43)
Visio file (limited access): https://drive.google.com/open?id=1sZWI4A4bfWD-eMfop-siR--ynPf2daD7

**Comment by jennmalcolm** [comment]
I would switch mine and lease because Solid's mines only have one operator at a time. Then I would link production from lease because you can have production on only some leases within a mine. Allocations vary month by month. We can discuss this once we get more into potential designs, but we may not need to display lease effective dates or submit type codes. Also, it would make more sense to put land class with lease.

**Comment by mcharg** [comment]
@jennmalcolm Better?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8ff95539-6396-4923-a471-2b7a4764553e)

**Comment by jennmalcolm** [comment]
Yes, it's looking better. I would still change to production date, and it should be lease effective date.

**Comment by mcharg** [comment]
@jennmalcolm Good?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/772f3051-b6bf-4574-8643-a3c669cb4323)

**Comment by jennmalcolm** [comment]
Yes @mcharg
