### ISSUE TITLE
Proposal for Federal Data Strategy data story

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3709]
Figure out what we need to do and do it.

-------------------

Good morning from the Federal Data Strategy team!

Has your agency used data to solve a problem in a creative way? Or do you work with data or know someone working to solve federal data problems? The Federal Data Strategy (https://strategy.data.gov/) team is looking for proof points as part of the incubator project.

These are stories by practitioners for practitioners, written in the style of the Harvard Business Review, and will be published on the Federal Data Strategy website. Some examples of topics include (but are not limited to): prioritizing datasets for release, experience assessing the privacy/disclosure risk of a given data asset, experience setting up a standard data sharing approach, using data to make a significant impact (save money,  save time, create new products etc.).

We will work with you and your team to develop the stories. This is a great way to share your knowledge with your peers and highlight the important work you do every day.

For further details please contact Bryant Renaud (OMB) at Bryant_D_Renaud@omb.eop.gov or me (rgiura@ftc.gov).

If you have content that has already been published and illustrates the impact of data produced by your agency please include the link or document.

**Comment by mcharg** [comment]
@brentryanjohnson I think changing to Gatsby, so program analysts can update the data sets on our site would be a good topic for this.  Thoughts?

**Comment by brentryanjohnson** [comment]
@mcharg and I met about this, and we decided to share some possible themes with their team and go from there.

**Comment by brentryanjohnson** [comment]
## Themes:

### Adapting our data publishing workflow: how we rebuilt our open data website
Covering some of the same terrain as [our blog post about refactoring our codebase](https://revenuedata.doi.gov/blog/homepage-revamp-part-two/), this story would largely cover why and how we made the decision to rebuild our open data site to create a more sustainable data publishing workflow for our team.

### How do we know which data to publish and how? We ask the people who use it.
This story would cover some of the same ground as our [blog post on redesigning our homepage based on user research](https://revenuedata.doi.gov/blog/homepage-revamp/). We can make assumptions about what our users need, but there's no substitute for asking them. In order to rebuild our open data homepage, we conducted a research round that led us to (1) start publishing monthly data (2) create a data summary on the homepage (3) summarize the categories of data up top and develop quick navigation and (4) add a "what's new" section to describe our latest updates to the site.

### How open-source tools and user-centered design principles helped prepare our agency for the 21st Century IDEA and OPEN Government Data Acts
The Natural Resources Revenue Data site, originally designed and developed by 18F, was built with tools and methods that largely anticipated recent legislation to modernize government websites and data practices. Our internal team at the Department of the Interior continues that legacy by expanding our user-research practices,  continuing to use exclusively open-source tools, and keeping our data, code, and workflow in the open.

### Mainstreaming our open-data tools and practices: how we share our work methods with our colleagues at the Department of the Interior
This story would be based in part on [our blog post about peer training for usability testing](https://revenuedata.doi.gov/blog/usability-testing-training/). Our small innovation design team works on an open-data site at the Office of Natural Resources Revenue, but we're limited to a maximum of four years in our respective roles. This story would cover how we're sharing our user-centered, open-data practices and tools with our career colleagues.

**Comment by mcharg** [comment]
Looks good, I would just modify the second one to be more about observation instead of asking.

How do we know which data to publish and how? We involve the people who use it.
This story would cover some of the same ground as our blog post on redesigning our homepage based on user research. We can make assumptions about what our users need, but there's no substitute for involving them and observing how they work with the data and our site. In order to rebuild our open data homepage, we conducted a research round that led us to (1) start publishing monthly data (2) create a data summary on the homepage (3) summarize the categories of data up top and develop quick navigation and (4) add a "what's new" section to describe our latest updates to the site.

**Comment by brentryanjohnson** [comment]
✔️ I emailed them with our themes on 3/20/19.
