### ISSUE TITLE
Address BLM comments about glossary terms and omissions

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3725]
> I reviewed you website and glossary and noticed that you published definitions for production but not sales, accounting years that use sales but not production, and no definition for production years.  This failure to delineate your information may cause it to be used incorrectly.
> 
> Thanks
> 
> From ONRRs glossary:
> 
> Production by Month | Documentation | Natural Resources Revenue Data
> We use the term “production” as a catch-all term for mining, drilling, energy generation, and other forms of natural resource extraction. There is no distinction between “extraction” and “production” in ONRR or EIA datasets.
> 
> Production by Month | Documentation | Natural Resources Revenue Data
> Accounting year data contains transactions for sales that took place in the current year, as well as adjusted or corrected transactions for sales that took place in previous years. Because they include adjusted or corrected transactions for previous sales periods, accounting year data should not be used for trending purposes or for analyzing sales volumes.
> 
> oddly enough ONRR has chosen not to define sales.
>

**Comment by brentryanjohnson** [comment]
I'm pulling this one in sprint for you to take a look at, @mentastc.

**Comment by Maroyafaied** [comment]
@mentastc @brentryanjohnson has anyone started to look into this? I'm a bit confused on what I should be looking into? Is it to define sales volume?

**Comment by brentryanjohnson** [comment]
@Maroyafaied I think the purpose is to:

- Decide if we're missing crucial information in the glossary, along the lines expressed by the individual from BLM

- ☝️ If we're missing crucial information, decide if the glossary is the right place to add the information, or if we need a new content asset somewhere else (how it works? downloads and docs?) to add the information, depending on scope

- Draft content for either or both instances of the content

There are at least two related issues: #3743 and #3359

**Comment by Maroyafaied** [comment]
@brentryanjohnson thanks for clarifying. I'll look into it.

**Comment by mentastc** [comment]
@Maroyafaied, do you wanna meet on this one and see if we can put something together?

**Comment by Maroyafaied** [comment]
Sure, I'm available today and my calendar is updated if you want to schedule something. Thanks!

**Comment by Maroyafaied** [comment]
Chris and I met and spoke about some ideas, I put together a google doc (limited access) capturing some of the recommendations. Feel free to comment or make any suggestions
https://docs.google.com/document/d/1jMctuCqsJxfDlaX2Q3RWDxSdb2V3D7pPW0kUdfDHDyI/edit#

**Comment by Maroyafaied** [comment]
I've added a suggested definition for "Accounting Year" to the document. Thoughts? @mentastc @brentryanjohnson @jennmalcolm

**Comment by Maroyafaied** [comment]
Suggested Accounting Year definition: This data is based on the revenue that was reported to and accepted into ONRR’s financial system in a given a year. Since companies are allowed to adjust and correct data up to seven years after a transaction takes place, this accounting year data includes corrections for sales that took place in previous years.  This data is most useful when analyzing dollars ONRR collected and disbursed in a given year.

**Comment by jennmalcolm** [comment]
I also talked to Nathan about this issue. He thought that the definition we have would be fine if we just take out the second sentence. I do like what you wrote @Maroyafaied, but since accounting year data isn't always revenue, maybe we could just say transactions. I know that takes away somewhat from clarity but is more accurate. @NBrannberg, do you have any feedback on the possible definition above?

**Comment by Maroyafaied** [comment]
@jennmalcolm , I edited the definition to say transactions rather then revenue.

**Comment by Maroyafaied** [comment]
will create another issue to change the Accounting year in the glossary and another issue to document when to use accounting year data vs sales year data for analysis.
