### ISSUE TITLE
Fix drop-down alignment in Firefox

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3937]
Organize by is below the others.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/2fa78960-8e57-4609-b21f-3aa7ba422104)

**Comment by brentryanjohnson** [comment]
@mcharg and @master12 This is due to the collision of and element with `overflow: hidden` and a subsequent `inline-block` element. Changing `hidden` to `visible` fixes this problem in Firefox, but it results in the year list overflowing the select list (when many years are selected). We'll have to find an alternative solution.

**Comment by mcharg** [comment]
@brentryanjohnson Is this done?

**Comment by brentryanjohnson** [comment]
Yes.
