### ISSUE TITLE
Audit data documentation

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3942]
We have documentation in 3 places: Wiki, data directory readme, and downloads and documentation.

This issue will be to do an audit of those places to determine what we have where.

**Comment by Maroyafaied** [comment]
@brentryanjohnson Are these links on the wiki for each type of data supposed to link to the document? None of the links work for revenue, production, or disbursement.
![image](https://user-images.githubusercontent.com/40175688/56368223-31dbb280-61b4-11e9-85f4-ce14a12d48c5.png)

**Comment by Maroyafaied** [comment]
(limited access) https://docs.google.com/spreadsheets/d/1VBUhiK0GypB2VnhEt-3yIhRMp2_LRz1wu95TgUqiHf0/edit#gid=1821009376

**Comment by Maroyafaied** [comment]
@lpgoldstein The READMe does not work anymore, so we are not auditing documents on there. We need to audit the wiki [Data Catalog ](https://github.com/ONRR/doi-extractives-data/wiki/Data-Catalog) for broken links, dates, missing document information, and removing references to README. Also decide on best location for documents and a place to describe how to use the data properly.

**Comment by brentryanjohnson** [comment]
@Maroyafaied and @lpgoldstein The README files are still available in older branches (before we migrated the directories fully to Gatsby). It's probably worthwhile to include these in the inventory, even for data that we are going to archive (since we may need to maintain that content in its archive state, at least to some extent). We should also archive these READMEs, which I can help with. The wiki already has an archive that may serve well for this purpose.

- [Main data README](https://github.com/ONRR/doi-extractives-data/blob/staging/data/README.md)
- [All production README](https://github.com/ONRR/doi-extractives-data/tree/staging/data/all-production)
- [Company README](https://github.com/ONRR/doi-extractives-data/tree/staging/data/company-revenue)
- [Disbursements README](https://github.com/ONRR/doi-extractives-data/tree/staging/data/disbursements)
- [Exports README](https://github.com/ONRR/doi-extractives-data/tree/staging/data/exports)
- [Federal production README](https://github.com/ONRR/doi-extractives-data/tree/staging/data/federal-production)
- [GDP README](https://github.com/ONRR/doi-extractives-data/tree/staging/data/gdp)
- [Geodata README](https://github.com/ONRR/doi-extractives-data/tree/staging/data/geo)
- [Jobs README](https://github.com/ONRR/doi-extractives-data/tree/staging/data/jobs)
- [Land ownership README](https://github.com/ONRR/doi-extractives-data/tree/staging/data/land-stats)
- [Reconciliation README](https://github.com/ONRR/doi-extractives-data/tree/staging/data/reconciliation)
- [Revenue README](https://github.com/ONRR/doi-extractives-data/tree/staging/data/revenue)

**Comment by lpgoldstein** [comment]
@brentryanjohnson  please look at our data audit sheet and then can we set up a meeting to talk about next steps?
