### ISSUE TITLE
Update Revenue by Company 

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#4072]
- [x] Check data to ensure it conforms to previous file format

- [x] Check data accuracy 

- [x] Update the revenue by company download file

- [x] update contextual language to reflect the additional year

- [x] Update the revenue by company visual 

Data File 
[federal_revenue_by_company_CY2013-CY2018 (3).xlsx](https://github.com/ONRR/doi-extractives-data/files/3173638/federal_revenue_by_company_CY2013-CY2018.3.xlsx)

**Comment by brentryanjohnson** [comment]
Notes on the origin data file versus historic files:

- The data files driving company revenue don't contain a year field, since each year is its own file.
- The new file column is "Corporate Name," versus "Company" in previous files.
- The new file column is "Revenues" versus "Revenue" in previous files.
