### ISSUE TITLE
Plan study to understand user questions

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4143]
- [x] Formulate study goals
- [x] Decide on appropriate questions for each user type
- [x] Come up with a recruiting strategy
- [x] Figure out how what we learn will work in with what we already know from previous studies.

**Comment by mcharg** [comment]
Draft plan (limited access): https://docs.google.com/document/d/1XD2lZ0AcLAFnhZXeg-SWgZoAgrV4xkou4lfsL5uqeTs/edit

Will be finalized after we finish going through the DORC requests.

**Comment by mcharg** [comment]
@jennmalcolm @Maroyafaied This is ready to review.  In particular, I'd like feedback on this form to rank the types of data that came out in the user question analysis.
https://docs.google.com/forms/d/e/1FAIpQLSfner9gFQ0TgmyIzjmGQqKr5UPtOpf-XafcvYrbZ7KtHFDrmQ/viewform

**Comment by usEITI** [comment]
The question about waste, seems a little bit leading or opinionated.  It is also a bit out of the norm for what is already on the site?

**Comment by usEITI** [comment]
No  I didn't mean to close only to close my comment

**Comment by Maroyafaied** [comment]
I like the form, it's a quick way to get perspective on what's important especially from users who don't have the time to do a full interview.

**Comment by mcharg** [comment]
@usEITI We've heard a bit about venting and flaring, which we would get at with lease level data.  Is there a better way to word it?

**Comment by usEITI** [comment]
The survey asks "How important are each of the following to you as far as data that's available on our website?"  We currently do not address venting and flaring.

**Comment by mcharg** [comment]
@usEITI It's meant to be data that could be on our website.

**Comment by mcharg** [comment]
@usEITI I reworded the question.

**Comment by mcharg** [comment]
@usEITI Would it be better to say "Information about what the operator did with the resources produced (venting, flaring, etc.)"

**Comment by usEITI** [comment]
the difference between sales volume and production is that which is not sold because it was used for producing on site, or because it was vented/flared to remove dangerous gases or reduce dangerous pressures, reasons  presumably for other than generating waste, bringing product up to sales quality etc.  The question could be providing information on volumes produced and not sold.

**Comment by jennmalcolm** [comment]
Not that it matters in terms of shaping the questionnaire (because I think the wording works as is), but my understanding is that a large portion of the flaring that occurs is due to new production where the gas takeaway capacity isn't available. In some locations, it is not economical to build the gas pipelines and what they're after is the oil (easily transported by truck or train). In some cases producers might prefer to continue flaring for the life of the lease, but the length of time they can flare is limited by federal regulations and some states' laws.

**Comment by jennmalcolm** [comment]
I checked the plan and put a couple comments/suggestions in the document. Otherwise looks good.
