### ISSUE TITLE
Determine guidance for data structure in downloads files

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4163]
We need to determine how to structure our data download files. For instance, in some files we separate month and date into two separate columns, while in others they are combined into one column. Each has use cases for which it is an advantageous approach.

We should decide on a guiding philosophy for our downloads data structure and use it consistently. We should also create documentation that explains our decision.

**Comment by jennmalcolm** [comment]
Part of the inconsistency stems from the files that we have not updated since we developed the [new recommended field names documented in this file](https://docs.google.com/spreadsheets/d/1YBKclvK8cAsvAVv9M14eJDQ7mYXlvGzqvMzeNycTlPk/edit#gid=668740044) (limited access). We should be separating the month and year in all of them. Still, we have not documented the reason for our decision to separte them, so we should do that in this issue. We could also revisit that decision if it because obvious that we've created significant user problems because of that decision (#3468).
