### ISSUE TITLE
Update NRRD outreach brochure

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/doi-extractives-data#4188]
Update NRRD outreach brochure

**Comment by lpgoldstein** [comment]
@mentastc  @jennmalcolm  @brentryanjohnson please take a look at the updated brochure and provide feedback.
[NRRD Outreach Brochure 2019_V6_06.20.2019.pdf](https://github.com/ONRR/doi-extractives-data/files/3311149/NRRD.Outreach.Brochure.2019_V6_06.20.2019.pdf)
 I updated the "new features" section based on the project plan but I'm not sure if the timeline is still accurate.

**Comment by mentastc** [comment]
We need to add the monthly revenue file similar to what we put there for production. For disbursements I would maybe say yearly instead of year and monthly instead of month; or maybe follow more closely to the format for production and revenue. 
![image](https://user-images.githubusercontent.com/15347998/59869091-80e2c700-9360-11e9-836f-02d504b709e1.png)

**Comment by lpgoldstein** [comment]
@mentastc and @jennmalcolm please take a look at the updated version
[NRRD Outreach Brochure 2019_V7_06.20.2019.pdf](https://github.com/ONRR/doi-extractives-data/files/3312866/NRRD.Outreach.Brochure.2019_V7_06.20.2019.pdf)

**Comment by jennmalcolm** [comment]
It's looking good. I noticed that disbursements alignment looks different than production and revenue in the data section. Also, could you remove the annual disbursements data updates from the new features because that doesn't really qualify as a new feature? Could you also take the build new state/offshore page design off that list? Let's keep the list of upcoming things narrowly focused on our top priorities (including longer term like lease level data).
