### ISSUE TITLE
Define revenue types in revenue trends

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4191]
Users in testing didn't know what the revenue types meant without a definition.

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0e379ee0-0267-411d-9b33-efbab43a7974)

**Comment by brentryanjohnson** [comment]
I've added the glossary pattern in the `trends-terms` branch. There are a couple problems:

- "Other revenues" in revenue trends contains categories that the download files do not (civil penalties, inspection fees). So a site-wide glossary term doesn't work in the current setup, because other revenue contains different things depending on where the user is at on the site (but the glossary term doesn't change based on which page the user is on)

- The collision of the glossary styling (especially the underline) with the sparklines isn't ideal visually, making it more difficult to interpret the sparkline.

![revenue trends showing royalties, rent, bonuses, other revenue, and total](https://user-images.githubusercontent.com/32855580/59794111-114fd780-928d-11e9-8a9c-b7ce3cc1fcd3.png)


Putting on pause until we resolve these.

**Comment by brentryanjohnson** [comment]
[:mag: Preview](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/trends-terms/)

**Comment by brentryanjohnson** [comment]
For me, "Total revenue" gets lost here, with the additional emphasis on the other rows. We should consider that as well.

**Comment by mcharg** [comment]
Regarding the first bullet, when we move the revenue trends under a revenue tab, we'll have more vertical space and can split out the civil penalties and inspection fees to be consistent.

Could we leave the underline off the glossary in this one instance and just use the question mark?  I think adding the definitions will benefit users enough to sacrifice styling and a little bit of consistency.

**Comment by jennmalcolm** [comment]
Here are a few options to address the lack of consistency with the term "other revenues":

1. Change trends to include two more lines, one for civil penalties and one for inspection fees and then "other revenues" will be the same in the file and the trends.

2. Change the civil penalty and inspection fees lines in the file to say "other revenues" in revenue type. Then we will need to change the definition for other revenues to reflect that it also includes inspection fees and civil penalties. I don't want to lose any level of detail in the data file, but it may be a reasonable trade off for ensuring that we're using the term "other revenues" consistently 

3. Use another term for the other revenues on the trends. I don't really like this option unless we can come up with a term that is clear and doesn't involve more investigating to figure out what it is. I don't have any ideas what that term would be, but maybe someone else does.

Here are my two top priorities in the solution:
1. Use the term consistently and clearly define what it is.
2. Make sure the revenue trends section continues to reflect the accurate total (doesn't leave out any revenues--which is something we need to address with the homepage revenue bar graph).

**Comment by mcharg** [comment]
#1 will be more feasible when we implement the new homepage, since we'll have more vertical space for the revenue trends.

**Comment by jennmalcolm** [comment]
Also in terms of the solution for making sure there is easy access to revenue type definitions, it might be cleaner just to provide a link to the scope and/or definitions (https://revenuedata.doi.gov/downloads/federal-revenue-by-month/#scope https://revenuedata.doi.gov/downloads/federal-revenue-by-month/#fields-definitions) where it currently talks about accounting year data . We can revise the scope to explain that it is accounting year data. I'm not sure that's a term we should introduce early on the homepage because most people don't care to understand the difference--and most really don't need to, especially if they're just interested in high-level trends like that section is showing.

**Comment by mcharg** [comment]
This is covered by putting glossaries in the intro paragraph on the new homepage.
