### ISSUE TITLE
Research options for database

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4239]
Figure out where to have it hosted, whether we should continue to use Federalist and add cloud.gov or other option.

**Comment by jennmalcolm** [comment]
After our initial discussion with Federalist, we've determined we need to continue our research by talking to Amazon Lambda contact and the College Scorecard team to decide on our strategy.

**Comment by master12** [comment]
Met with College Scorebaord. Their setup is as follows:
1 Federalist - for website builds using jekyll
2 Cloud.gov - for api and elastic search
3 Data.gov - for data storage

The decision to keep federalist and cloud.gov had to do with keeping things simple since they already had federalist running. They did not see a need to just use cloud.gov despite cost. They were not sure if there is a cost associated with data.gov
