### ISSUE TITLE
Build mobile for homepage tabs

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4419]

**Comment by mcharg** [comment]
Prototype with tabs on top.
https://sjzq35.axshare.com/#g=1&p=alt_tab_styling&view=a

**Comment by mcharg** [comment]
@mojobnichols 

Here's the list of what's left (since it's a little hard to track in the PR):
- [ ] Revenue trends cuts off on the right on mobile.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/3decaac9-082f-45e4-b32d-ce8255eb83fb)

- [ ] Disbursements trends cuts off on the right on mobile.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d04c787b-b16a-49e9-8a7a-c1d628c2e803)

- [ ] State copy cuts off on the right on mobile.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/21f68c8b-3356-4f22-ade8-adabb9c693eb)

- [ ] In the mid-width views with one column, the trends should be the same width as the graph.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/5a129b2e-1092-4d00-a4b1-9e01c408dc98)

- [ ] For the links, there should be either 3 columns or 1. Two columns breaks up the content weirdly. The how it works link should go above the documents here as a 1 column view.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0985d4a1-4c5b-4416-b380-baa876180dd4)

- [ ] The map still doesn't build in Edge and Firefox.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/241df51c-2704-4d59-8036-38dad3a7dc5a)
