### ISSUE TITLE
Rounding in revenue trends section is off

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4442]
Some of the rounding in the revenue trends looks ok, but I just compared the total in the data file to what's in the revenue trends file, and some of the rounding is strange. It rounds 109,587,822 for the other revenues total to 110.00 million. It also rounds the total from 10,380,751,869 to 10.40 billion. I was thinking that since both the other revenues and the total are sums of other number perhaps we're adding the rounded numbers rather than adding and then rounding, but when I added the rounded numbers in the revenue trends section, I got a total of 10.374 billion for the total. I think we should always add and then round, so that the numbers match with the source data file.

![image](https://user-images.githubusercontent.com/30806839/63093654-13a07c00-bf34-11e9-8a64-ff63be2c97bb.png)

![image](https://user-images.githubusercontent.com/30806839/63093680-2adf6980-bf34-11e9-8b02-111810c08769.png)

**Comment by mojobnichols** [comment]
d3.format is used to format the large number to a precison of 3.  Unfortunately d3 considers the whole number so numbers with modulus 3  equal to 0 causes it to truncate remaining digits(128,099,000 becomes 128M) .   We then format to 2 decimal places (128M becomes 128.00 instead of 128.10).   The solution is to add 2 to the precision of d3 format.   This seems to work in all cases as the rounding is then done correctly.

**Comment by jennmalcolm** [comment]
Fixed by #4596
