### ISSUE TITLE
Define what data the revenue trend line should use

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4489]
It's currently using a mix of FY and monthly data.  We should decide whether we want it to use either all FY or all monthly.

**Comment by jennmalcolm** [comment]
This seems like a bigger problem now that we have one month of 2020. It seems like it is comparing the one month of 2020 to the full years. It should either use a rolling 20-years worth of the monthly data and smooth out the line, or if that's not possible, the trend line should only use complete years, and then it should have the years at the top (e.g. "FY 2010-2019 trend" rather than just saying "10-year trend"). 
![image](https://user-images.githubusercontent.com/30806839/69064953-ec52c280-09ec-11ea-84ed-e81d69be9368.png)
The trend should not look like everything is down drastically because that is mis-representing what is really happening.

**Comment by jennmalcolm** [comment]
Another option to be able to incorporate the current year would be to divide the previous nine years each by 12 divide by the number of months we have in the current year. For example, divide 2010 through 2019 each by 12 since we only have one month of 2020 now. When we get November, we would divide each year's revenues by 6. When we get December, we would divide revenues in each year (except 2020) by 4, and so on. This will give you comparable averages.

**Comment by master12** [comment]
So is the issue the trend line?

**Comment by jennmalcolm** [comment]
yes, @master12 and I think it is because 2020 only has one month of data, but it is still using 2020 in the trend line.

**Comment by jennmalcolm** [comment]
Can you see what it would look like to use all monthly data vs my second suggestion with averages?

**Comment by jennmalcolm** [comment]
Here's what it would look like using the averaging method (in Excel at least) for this month.

![image](https://user-images.githubusercontent.com/30806839/69071246-959eb600-09f7-11ea-943c-e16e8a45e0ef.png)

**Comment by master12** [comment]
yay pretty ugly by month
![image](https://user-images.githubusercontent.com/6054679/69075934-66d90d80-0a00-11ea-8b35-98f8a72f1d2c.png)

**Comment by jennmalcolm** [comment]
Any thoughts on this, @mcharg and @brentryanjohnson?

**Comment by mcharg** [comment]
Ugly is better than inaccurate or misleading.  I think we would have to explain the averaging method somewhere if we went that route.

**Comment by master12** [comment]
or we could leave off the current year

**Comment by brentryanjohnson** [comment]
I think if we're going to trend with monthly data, we should convert the 10-year to a 1-year and just track the past 12 months. If we're going to do 10 year, I think we should just use annual data and not monthly, so we're comparing apples to apples.

**Comment by jennmalcolm** [comment]
@brentryanjohnson what about using monthly data but only for the last 3 years or something shorter than the 10 years? I just think either full years or the last 12 months is no different than the data available on the bar graphs.

**Comment by jennmalcolm** [comment]
I guess for now we can just leave off the current year until we have the full year. At least it will be accurate. It just doesn't seem to add value over the bar graphs in my mind. In that case, let's change the heading to state the years (e.g. 2010-2019 trend).
