### ISSUE TITLE
Update LWCF data 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/doi-extractives-data#4561]
We need to update our LWCF data since most recent distribution has been announced to the public: https://www.doi.gov/pressreleases/secretary-bernhardt-announces-1706-million-support-state-parks-and-outdoor-1

- [x] Is there an internal database where we can access that data? 
- [x] Establish an LWCF contact in the NPS

**Comment by Maroyafaied** [comment]
We don't currently have this data mentioned on your website (disbursements by state).  LWCF's website has the reports published till 2016. I have contacted someone about when they will update the website with current reports, she send me the pdfs for 2017-2019 and stated that they are working on making the documents as well as everything on the website Section 508 compliant. She stated they don't have a specific timeline of when this will happen.

  I recommend we don't post individual pdfs and continue to link to LWCF's website since in the near future they will be posting more recent reports showing data for each state.

**Comment by brentryanjohnson** [comment]
Ideally, we would provide the data in csv, tsv, or Excel ([as we used to](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/staging/downloads/disbursements/#archive)), but if they don't have it in such a format, then I suppose that isn't an option.

It looks like #1730 tracks the point at which LWCF data was added to the site, but unfortunately, it doesn't record the source of the data.

**Comment by Maroyafaied** [comment]
@brentryanjohnson I can ask my contact if she can provide the data in an excel format.

**Comment by Maroyafaied** [comment]
`I have not heard back from the contacts I emailed about getting these reports in excel format.

**Comment by Maroyafaied** [comment]
@jennmalcolm I haven't heard anything from my contact from LWCF. I'm doubting that we can get these files in excel files. I can give you the contact info if you'd like to try or we can close this issue.

**Comment by jennmalcolm** [comment]
I'll give it a try if you email me the contact info.

**Comment by Maroyafaied** [comment]
@jennmalcolm  the participant for the user interview we did yesterday gave us a contact for LWCF data. I will reach out to that contact as well to see if I can get the excel files.

**Comment by jennmalcolm** [comment]
Ok, great. I haven't called yet anyway, so let me know what happens.
