### ISSUE TITLE
Revenue Table display of not tied to location 

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#4586]
The revenue table currently excludes most of the revenue that isn't tied to a location when sorting by location. For instance civil penalty and inspection fee revenue won't show up, however there is some not tied to location revenue that does show up, this is inconsistent and we should decided whether or not the revenue should show up.

![image](https://user-images.githubusercontent.com/15347998/65169284-3b43a200-da14-11e9-8347-777c41f2e79a.png)

**Comment by master12** [comment]
Here is the logic I have for Not tied to location:
Land category = 'Not tied to a lease' or
Revenue type = 'Civil Penalties' or
Revenue Type = 'Other Revenues' 

If that is true then we checK:
Land Class does NOT equal Native american AND
Offshore Region is blank

if that is true then we check:
if State is blank assign 'Not tied to location'

**Comment by master12** [comment]
Did find issue with current code. Misspelled Civil Penalties so I am fixing that

**Comment by jennmalcolm** [comment]
You are missing that the revenue type could also be "Inspection Fees." So, I think you could just add that to the revenue type part of your logic, but I actually don't think that's necessary. I think we could do it simpler and just keep:

IF
Land class equals Federal (equivalent to does not equal Native Amercan) AND
State is blank AND
Offshore Region is blank
THEN
assign "Not tied to a location"

The numbers we are looking for for the Not tied to location line are as follows (example for 2016-2018)
![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/43284329-13fe-41d3-83ea-194d70cb97a2)

The grand total line should match with the totals from the Excel file (example for 2016-2018), with potential for a small variance due to rounding:
![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/8dc217d1-307e-4e8c-b883-bc7bc614d577)

**Comment by jennmalcolm** [comment]
Fixed by #4640
