### ISSUE TITLE
Query Tool Logic Updates

### ISSUE THREAD

**Issue by master12** [ONRR/doi-extractives-data#4616]
Update the logic for the query tool

**Comment by mcharg** [comment]
Here's all the open issues from the previous PR.
## Logic changes (apply to both revenue and production)

### Land category
- [ ] If "All land categories" is selected, the Native American withheld note needs to be displayed and the user shouldn't be able to select a location.
- [ ] If "Onshore" is selected, the Native American withheld note needs to be displayed and the user shouldn't be able to select a location.
- [ ] Add "Select a federal-only land category to view location." to the end of the Native American withheld note.

### Location
- [ ] The County (or Burrough or Parish) drop-down should display if you select a single state from the list.
- [ ] A CPS drop-down should display if you select a single offshore region from the list.

### Commodity
- [ ] The commodity drop-down should only display commodities that exist for the previous selections.
- [ ] The "All" checkbox should select/unselect all the other checkboxes when it's checked or unchecked.

### Years
- [ ] The end year should only display years that occur after the selected start year.
- [ ] The years should be ordered from oldest to newest.

### Default columns
- [ ] Add the name of the first column to the accordion label.
- [ ] There are different default first and second columns depending on the selections. See the logic spreadsheet Columns F & G for the defaults (or you can get on a Hangout with @mcharg and work through it - I'm not going to type it all again).
- [ ] If there's only one option available for the columns, the "Edit grouping" button should hide. This occurs when there is only one way the data can be broken out (for example, if you pick a single commodity, you can no longer break out the data by commodity). See the spreadsheet Column H for cases where this happens.

## No data changes (applies to all data sets)
- [ ] Only display rows when there is data for at least one year the user has selected.
- [ ] If there are years with no data in the user's selection, but numbers for at least one other visible year, the years with no data get a dash.

## Revenue changes
- [ ] How It Works link should be "How revenue works" and use the How it works icon from the homepage.

## Production changes
- [ ] The header on the table should be "Production", not "Revenue".
- [ ] I think it's still showing revenue data when production is selected because it's showing in dollars and the commodity label doesn't show the units. - Update: This appears to only happen when you select production after you've selected revenue.  I'm now seeing production data when I select that first.
- [ ] Measurements are missing for everything except geothermal.
- [ ] Revenue type isn't a column for production, so it shouldn't be a filter.
- [ ] Rows with only withheld data should be hidden by default with a checkbox to add them in. 
![image](https://user-images.githubusercontent.com/38465926/66073554-3ce98b80-e525-11e9-86f3-d01f13c66d41.png)
- [ ] How It Works link should be "How production works" and use the How it works icon from the homepage.

## Access to the table
- [ ] Set up the page, so we can link to revenue, production, or disbursements.
- [ ] Add "Filter production data" and "Production in detail" links to the Production homepage tab following the same pattern as the Revenue links.
- [ ] Add "Filter disbursements data" and "Disbursements in detail" links to the Disbursements homepage tab following the same pattern as the Revenue links.
- [ ] Add "Production data in detail" link to the left of the documentation link on the Explore data page.
- [ ] Add "Disbursements data in detail" link to the left of the documentation link on the Explore data page.
- [ ] Update the icon on the "Revenue data in detail" links to the table icon (see #4646).

## Fit and finish
- [ ] Make it so we don't cut off content when there are a large number of columns.  It's unusable if you can't read the numbers or labels.
![image](https://user-images.githubusercontent.com/38465926/66214666-27dd3b80-e690-11e9-9b5c-6412c42aba6e.png)

**Comment by jennmalcolm** [comment]
Continued in #4679
