### ISSUE TITLE
Explore Data: Revenue cards

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4699]
Design and build cards for nationwide and state revenue.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/fdde9929-ac01-41f3-a230-7adbc047b687)

**Comment by mojobnichols** [comment]
The build is not working in circle ci (not related to revenue cards) so I'm forgoing a PR and focusing on the cloud.gov production task (which involves getting ci working).   That said all the data is in the cards so I wanted Shannon to get an early look at my development environment.  It's still rough visually and I will probably split off a style revenue cards since I think this task has earned it's 5 points already.    @mcharg when your in let's schedule a time to go over it.

**Comment by mcharg** [comment]
@mojobnichols I'm pretty open today if you want to schedule some time.
