### ISSUE TITLE
Improve map coloring and visual design

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4700]
Define what colors to use for the map and any other visual design considerations.

Includes #4448 to use greens in our color palette.

**Comment by mojobnichols** [comment]
Some fundamental stuff was done to improve this custom colors and separating legend from map.  As well as getting into mui themes etc.    I vote this be closed at least for build side since it is significantly vague and open ended.   For example panning and zooming should be added to the map next as it will impact any other further improvement but this should just be its own issue.

**Comment by mojobnichols** [comment]
Closing since some improvements were made and its linked  to wrong repo.
