### ISSUE TITLE
Create cloud.gov migration plan

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4760]
We should have the IAA done on ONRR's side this week, and then depending on 18-F's timing for signing, we can get started with our paid version. This issue will be to determine and document the migration plan for this transition.

**Comment by mojobnichols** [comment]
Cloud.gov migration plan

Overview

The use of cloud.gov presents some opportunities such as database use, circle ci integration and a new environment with new caveats, idiosyncracies, and features.   Rather then lift and shift (rehost) the current environment into clould.gov environment and then refractor the code to use the new features.   It is recommended that we replatform (aka lift and shape) the code directly into the new environment.   This strikes a nice balance between basic rehost and rehost with refractor.  By replatforming we will pull functionality and refractor the minium required to make it utilize new features.  A major advantage of this is that 100% of refractoring will be done with no remaining refractoring tech debt.   This is because in replatforming the site is migrated component by component and no component is migrated without the refractoring done.


Figure 1. Rehost vs Replatform vs Refactor









There are three main thrusts that will be needed to replatform from the old site to the new site. 

Thrust 1.   Migrate base site with layout.    The only refractoring is completely using material ui vs material ui,  css, scss and module.css.  

Thrust 2.   Feature migration.  Each component are brought over and one by one.  The only refractoring will be to migrate from redux to apollo for data and state managment

Thrust 3.   Other this will be anything remaining that was not part of layout or a “feature”,  or basically content.   This will be the easiest as this won’t require any refractoring.  It may be desirable to clean up unnecessary content


Conclusion

By lifting and reshaping we can take the opportunity to leave unmigrated old tech debt behind.  We can maintain the current sit and even enhance.  We can show the progress internally in short iterations and gather feedback on any technicalities that occur.   The technological approach can be adjusted if necessary when/if needed.  The main drawback is that with lift and shift approach the entire site can be up in a day, but then the refactoring is still required.  The main benefit to replatforming is that the code will be free of multiple approaches or left over unrefactored code.   This will result in future design changes and feature enhancements being much easier to implement.
