### ISSUE TITLE
Create summary tables for best use of data and characteristics of the data sets.

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#4849]
This is continuing work on issue #4725. We need to provide context for a user to know how the data relates and which data sets they should use for their purposes. To do so, we will create a summary table for best use of data and another summary table for characteristics of data. For best use of data, we will reference search terms and the user questions tasks spreadsheet. 

https://doimspp-my.sharepoint.com/:x:/g/personal/mchargs_mms_gov/EZFb-HAw_cJFmJbnT1qeKsIB72-VQwB0FHgKMvRMupiLuw?e=zXnFRN

https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B40D65BB0-7DB5-4AAC-B940-52A0C70207BC%7D&file=User%20questions.xlsx&action=default&mobileredirect=true

**Comment by Maroyafaied** [comment]
@jennmalcolm here is what we have so far. https://doimspp-my.sharepoint.com/:x:/r/personal/faiedm_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B7A39F36D-4C1F-4851-BC59-3428E50D0F96%7D&file=Best%20use%20of%20data.xlsx&action=default&mobileredirect=true

**Comment by Maroyafaied** [comment]
@brentryanjohnson when you have time , can you review this since Jennifer is out. Thanks!

**Comment by brentryanjohnson** [comment]
@Maroyafaied and @lpgoldstein There's a lot of content to sift through here. I wonder if it might be useful to modify it in one of three ways:

1. Structure the existing listings under "like" categories, such as "Companies, "Commodities," "Native Americans," etc.
1. Break the list into two separate lists, one for the characteristics of what's in each data set (the "see" rows) and one for the uses of the data (the "calculate," "analyze" rows)
1. Eliminate the "see" rows and only present the "do" rows (calculate, analyze, etc.)

A hypothesis to consider: we show a lot of the "see" characteristics in our data visualizations. Since this table accompanies the raw data files, I wonder if we might want to focus on the calculations, analyses, and manipulations of the raw data that users might want to do. We could still present some of the "see" rows here, by changing the wording. For instance, "calculate gas vented or flared over time," instead of "see how much waste is happening..."

Let's talk about it sometime this week, if you both have time.

**Comment by Maroyafaied** [comment]
We discussed this and decided to create another issue to come up with a simple design/display to let the user know best use cases and misuse of each data set such as a green check mark for correct use and a red X for misuse. This would let the user know the fields and tasks the raw data could be used for.
