### ISSUE TITLE
blog post on shaping and new site

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#5042]

**Comment by mcharg** [comment]
@jennmalcolm I started by copying the relevant pieces from the Code for America presentation into a doc that we can turn into a narrative.  I'm thinking we should add more about the build piece, since we already covered most of the shaping pieces in the remote design studio post.
https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7BBC978A2B-3FB7-48D1-A0D4-DF822D6FBC4B%7D&file=Shaping.docx&action=default&mobileredirect=true&CT=1590781880807&OR=ItemsView

**Comment by jennmalcolm** [comment]
I will work on this tomorrow @mcharg

**Comment by jennmalcolm** [comment]
@Maroyafaied and @lpgoldstein could you take a look at our draft in the above document and give us your feedback before we put it in a PR?

**Comment by lpgoldstein** [comment]
@jennmalcolm I really enjoyed reading this. It documents what we did for this update and how it has played out and now we can use this blog post as guidance for our next big project.
